### ISSUE TITLE
Portal not working for 1.12.2

### ISSUE THREAD

**Issue by poopybutt12** [Sunekaer/YAMDA#10]
I play on 1.12.2 singleplayer. I can place the portal and everything fine but when i right click it nothing happens. 
-I also have many other mods active, but if one of them is causing the issue, idk which one.

**Comment by Sunekaer** [comment]
Log?

**Comment by poopybutt12** [comment]
This is just the warns. There were no errors or fatal. I didnt put anything from info or debug because it wont let me copy the whole thing

12:33:23.138
launcher
main
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar
12:33:23.139
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\versions\1.12.2\1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.139
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838.jar
12:33:23.141
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2838\forge-1.12.2-14.23.5.2838.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.177
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
12:33:23.178
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar
12:33:23.179
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.179
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.215
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
12:33:23.216
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.230
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
12:33:23.231
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.243
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
12:33:23.244
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.255
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
12:33:23.256
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.263
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
12:33:23.264
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.277
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
12:33:23.279
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.295
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
12:33:23.297
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.306
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
12:33:23.308
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:23.341
launcher
main
Couldn't fetch SHA1 checksum for http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
12:33:23.341
launcher
main
Have local file C:\Users\Brennen\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
12:33:44.000
launcher
main
Version does not support log configuration, will assume one plaintext entry per line

**Comment by poopybutt12** [comment]
Every time i right click the portal i get this...


[12:51:00] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
12:51:00.642
game
java.util.concurrent.ExecutionException: kotlin.TypeCastException: null cannot be cast to non-null type net.minecraftforge.common.capabilities.CapabilityDispatcher
12:51:00.642
game
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
12:51:00.642
game
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
12:51:00.642
game
at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
12:51:00.642
game
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
12:51:00.642
game
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
12:51:00.642
game
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
12:51:00.642
game
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
12:51:00.642
game
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
12:51:00.642
game
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type net.minecraftforge.common.capabilities.CapabilityDispatcher
12:51:00.642
game
at de.johni0702.minecraft.betterportals.common.ExtensionsKt.getForgeCapabilities(Extensions.kt:269) ~[ExtensionsKt.class:?]
12:51:00.642
game
at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler$transferPlayerToDimension$view$1.invoke(DimensionTransitionHandler.kt:25) ~[DimensionTransitionHandler$transferPlayerToDimension$view$1.class:?]
12:51:00.642
game
at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler$transferPlayerToDimension$view$1.invoke(DimensionTransitionHandler.kt:13) ~[DimensionTransitionHandler$transferPlayerToDimension$view$1.class:?]
12:51:00.642
game
at de.johni0702.minecraft.betterportals.server.view.ServerViewManagerImpl.createView(ServerViewManagerImpl.kt:75) ~[ServerViewManagerImpl.class:?]
12:51:00.642
game
at de.johni0702.minecraft.betterportals.server.DimensionTransitionHandler.transferPlayerToDimension(DimensionTransitionHandler.kt:23) ~[DimensionTransitionHandler.class:?]
12:51:00.642
game
at net.minecraft.server.management.PlayerList.handler$betterPortalPlayerToDimension$zzl000(PlayerList.java:1307) ~[pl.class:?]
12:51:00.643
game
at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java) ~[pl.class:?]
12:51:00.643
game
at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:695) ~[oq.class:?]
12:51:00.643
game
at com.sunekaer.mods.yamda.util.WorldTeleporter.teleport(WorldTeleporter.java:64) ~[WorldTeleporter.class:?]
12:51:00.643
game
at com.sunekaer.mods.yamda.block.BlockPortal.func_180639_a(BlockPortal.java:56) ~[BlockPortal.class:?]
12:51:00.643
game
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
12:51:00.643
game
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
12:51:00.663
game
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
12:51:00.663
game
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
12:51:00.663
game
at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
12:51:00.663
game
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
12:51:00.663
game
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
12:51:00.663
game
at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
12:51:00.663
game
... 5 more

**Comment by Sunekaer** [comment]
Please use https://paste.feed-the-beast.com that there is unreadable and post the full log

**Comment by FemStranger** [comment]
I'm having the same issue on 1.14.4.
Log: https://paste.feed-the-beast.com/view/9175137b

**Comment by Sunekaer** [comment]
@FemStranger please make a new issue..

**Comment by poopybutt12** [comment]
https://paste.feed-the-beast.com/view/151af42a

**Comment by Sunekaer** [comment]
look like kotlin or betterportals causing the issue
