### ISSUE TITLE
Cant make mining dimension with modded ores

### ISSUE THREAD

**Issue by FullMetalMaster** [Sunekaer/YAMDA#7]
when other mods are instailled Yamda cant gen any of the ores and there for can not load the mining dim

log: [07Jul2019 08:22:22.700] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: Dimension type must not be null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[server-1.14.3-extra.jar:?]
	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:157) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:958) ~[?:?]
	at com.sunekaer.mods.yamda.block.BlockPortal.func_220051_a(BlockPortal.java:58) ~[?:3.0.3]
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:876) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[07Jul2019 08:22:22.846] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: Dimension type must not be null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[server-1.14.3-extra.jar:?]
	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:157) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:958) ~[?:?]
	at com.sunekaer.mods.yamda.block.BlockPortal.func_220051_a(BlockPortal.java:58) ~[?:3.0.3]
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:876) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[07Jul2019 08:22:22.847] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: Dimension type must not be null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[server-1.14.3-extra.jar:?]
	at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:157) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:958) ~[?:?]
	at com.sunekaer.mods.yamda.block.BlockPortal.func_220051_a(BlockPortal.java:58) ~[?:3.0.3]
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:876) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[07Jul2019 08:22:51.943] [Server thread/WARN] [net.minecraft.world.TrackedEntity/]: Fetching packet for removed entity ItemEntity['Air'/635, l='SMP Live Moded Beta', x=1398.67, y=73.00, z=-2766.20]

**Comment by Sunekaer** [comment]
What mod is causing the problem?
i have it installed with 18 other mods without problem

**Comment by Sunekaer** [comment]
#6 stay in one issue...
